In [ ]:
pip install pandas

In [2]:
import pandas as pd
data=[1,2,3,4,5]
#converting list to series
#indices will be the default indices and values will be the values of the list
series=pd.Series(data)
print(series)
print(type(series))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [ ]:
#converting Dictionary to series
#indices will be the keys of the dictionary and values will be the values of the dictionary
data={'a':1,'b':2,'c':3}
series=pd.Series(data)
print(series)

In [ ]:
data=[10,20,30,40,50]
index1=['a','b','c','d','e']
index2=[1,2,3,4,5]
#converting list to series with custom indices
series1=pd.Series(data,index=index2)
series2=pd.Series(data,index=index1)
print(series1)
print(series2)

In [3]:
#converting Dictionary to DataFrame
data={'Name': ['Alice', 'Bob', 'Charlie', 'David'],
      'Age': [25, 30, 35, 40],
        'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']}
df=pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
<class 'pandas.DataFrame'>

In [28]:
df=pd.read_csv('sales_data.csv')
# or df=pd.read_csv('C:\\Users\\dilee\\OneDrive\\Desktop\\python\\sales_data.csv')
# can also past the path of the file in the read_csv function to read the csv file from any location
df.head() #to display first 5 rows of the dataframe by default

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [29]:
df['Product Name'] #to display specific columns of the dataframe

0                                        iPhone 14 Pro
1                                     Dyson V11 Vacuum
2                                     Levi's 501 Jeans
3                                    The Da Vinci Code
4                              Neutrogena Skincare Set
                            ...
235    Nespresso Vertuo Next Coffee and Espresso Maker
236                          Nike Air Force 1 Sneakers
237             The Handmaid's Tale by Margaret Atwood
238               Sunday Riley Luna Sleeping Night Oil
239                         Yeti Rambler 20 oz Tumbler
Name: Product Name, Length: 240, dtype: str

In [30]:
df.loc[0, 'Product Name'] #to display specific value of the dataframe using loc function

'iPhone 14 Pro'

In [31]:
df.loc[0,:] #to display specific row of the dataframe using loc function

Transaction ID              10001
Date                   2024-01-01
Product Category      Electronics
Product Name        iPhone 14 Pro
Units Sold                      2
Unit Price                 999.99
Total Revenue             1999.98
Region              North America
Payment Method        Credit Card
Name: 0, dtype: object

In [34]:
df.loc[[0,1,2],:] #to display specific rows and columns of the dataframe using loc function

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card

In [36]:
df.loc[0:2,:] #to display specific rows and columns of the dataframe using slicing

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card

In [41]:
df.loc[0:2]#to display specific rows of the dataframe using slicing

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card

In [40]:
df.loc[0:5, ['Product Name', 'Units Sold']] #to display specific rows and columns of the dataframe using loc function

                  Product Name  Units Sold
0                iPhone 14 Pro           2
1             Dyson V11 Vacuum           1
2             Levi's 501 Jeans           3
3            The Da Vinci Code           4
4      Neutrogena Skincare Set           1
5  Wilson Evolution Basketball           5

In [50]:
df.loc[0:8, ['Product Name', 'Unit Price']].head()#to display specific rows and columns of the dataframe using loc function

              Product Name  Unit Price
0            iPhone 14 Pro      999.99
1         Dyson V11 Vacuum      499.99
2         Levi's 501 Jeans       69.99
3        The Da Vinci Code       15.99
4  Neutrogena Skincare Set       89.99

iloc:

In [52]:
df.iloc[[0,7],[0,3]] #to display specific rows and columns of the dataframe using iloc function

   Transaction ID          Product Name
0           10001         iPhone 14 Pro
7           10008  Blueair Classic 480i

note: for Slicing, in loc: the last index in included(n). Where as in iloc, last index is excluded(n-1)

In [53]:
df.iloc[0:2, 0:4] #to display specific rows and columns of the dataframe using slicing with iloc function

   Transaction ID        Date Product Category      Product Name
0           10001  2024-01-01      Electronics     iPhone 14 Pro
1           10002  2024-01-02  Home Appliances  Dyson V11 Vacuum

In [ ]:
df.iloc[0:5,:] #to display specific rows of the dataframe using slicing with iloc function
#or df.iloc[0:5] #to display specific rows of the dataframe using slicing with iloc function

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

at and iat: TO display the one and only specific data of the specified name (in at) or index (in iat)

In [56]:
df.at[0, 'Product Name'] #to display specific value of the dataframe using at function

'iPhone 14 Pro'

In [61]:
df.iat[1, 2] #to display specific value of the dataframe using iat function

'Home Appliances'

Data Manipulation/Transformation:

In [64]:
data={'Name': ['Alice', 'Bob', 'Charlie', 'David'],
      'Age': [25, 30, 35, 40],
        'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']}
df=pd.DataFrame(data)
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston

In [65]:
#Adding a new column to the DataFrame
df['Country'] = ['USA', 'USA', 'USA', 'USA']
df['Salary'] = [50000, 60000, 70000, 80000]
df

      Name  Age         City Country  Salary
0    Alice   25     New York     USA   50000
1      Bob   30  Los Angeles     USA   60000
2  Charlie   35      Chicago     USA   70000
3    David   40      Houston     USA   80000

In [66]:
#Deleting a column Temperorily from the DataFrame
df.drop('Salary', axis=1) #to delete a column from the DataFrame using drop function

      Name  Age         City Country
0    Alice   25     New York     USA
1      Bob   30  Los Angeles     USA
2  Charlie   35      Chicago     USA
3    David   40      Houston     USA

In [ ]:
df

      Name  Age         City Country  Salary
0    Alice   25     New York     USA   50000
1      Bob   30  Los Angeles     USA   60000
2  Charlie   35      Chicago     USA   70000
3    David   40      Houston     USA   80000

In [68]:
#Deleting a column from the DataFrame permanently
df.drop('Salary', axis=1, inplace=True) #to delete a column from the DataFrame permanently using drop function with inplace parameter set to True

In [69]:
df

      Name  Age         City Country
0    Alice   25     New York     USA
1      Bob   30  Los Angeles     USA
2  Charlie   35      Chicago     USA
3    David   40      Houston     USA

In [71]:
df.drop('Country', axis=1, inplace=False) #to delete a column from the DataFrame permanently using drop function with inplace parameter set to False

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston

In [73]:
df
#we can delete a column temperorily by both not using inplace parameter or by setting inplace parameter to False. But if we want to delete a column permanently we have to set inplace parameter to True.

      Name  Age         City Country
0    Alice   25     New York     USA
1      Bob   30  Los Angeles     USA
2  Charlie   35      Chicago     USA
3    David   40      Houston     USA

In [ ]:
df.drop([0], axis=0, inplace=False)
#to delete a row from the DataFrame Temperorily using drop function with inplace parameter set to True

      Name  Age         City Country
1      Bob   30  Los Angeles     USA
2  Charlie   35      Chicago     USA
3    David   40      Houston     USA

In [75]:
df

      Name  Age         City Country
0    Alice   25     New York     USA
1      Bob   30  Los Angeles     USA
2  Charlie   35      Chicago     USA
3    David   40      Houston     USA

In [ ]:
import pandas as pd
df=pd.read_csv('data.csv')
df.head()

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    NaN   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    NaN  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    NaN  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    NaN  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    NaN   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    NaN   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    NaN  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [ ]:
df.describe()
#Statistical summary of the DataFrame using describe function

           Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [20]:
#isnull() function is used to check for missing values in the DataFrame. It returns a DataFrame of the same shape as the original DataFrame, with True indicating missing values and False indicating non-missing values.
df.isnull().head()

    Date  Category  Value  Product  Sales  Region
0  False     False  False    False  False   False
1  False     False  False    False  False   False
2  False     False  False    False  False   False
3  False     False  False    False  False   False
4  False     False  False    False  False   False

In [ ]:
#any() function is used to check if any of the values in the DataFrame are missing. It returns a boolean value indicating whether any of the values are missing or not. if atleast one value is missing in the DataFrame it will return True otherwise it will return False.
df.isnull().any()

Date        False
Category    False
Value        True
Product     False
Sales        True
Region      False
dtype: bool

In [15]:
#sum() function is used to count the number of missing values in each column of the DataFrame. It returns a Series with the column names as the index and the number of missing values as the values.
df.isnull().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [26]:
#replaces all null values with the specified given value. here:0
df1=df.fillna(0)
df1.head(10)

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North
5  2023-01-06        B   54.0  Product3  192.0   West
6  2023-01-07        A   16.0  Product1  936.0   East
7  2023-01-08        C   89.0  Product1  488.0   West
8  2023-01-09        C   37.0  Product3  772.0   West
9  2023-01-10        A   22.0  Product2  834.0   West

In [ ]:
Value_mean=df1.Sales.mean()
Value_mean
#to calculate the mean of the Sales column in the DataFrame df1 using the mean() function. The result is stored in the variable Value_mean and then printed to the console.

np.float64(512.56)

In [39]:
#filling null values with the mean of the 'Value' column from df1
df['Values_fillNA']=df['Value'].fillna(df1.Value.mean())
df.head(16)

          Date Category  Value   Product  Sales Region  Values_fillNA
0   2023-01-01        A   28.0  Product1  754.0   East          28.00
1   2023-01-02        B   39.0  Product3  110.0  North          39.00
2   2023-01-03        C   32.0  Product2  398.0   East          32.00
3   2023-01-04        B    8.0  Product1  522.0   East           8.00
4   2023-01-05        B   26.0  Product3  869.0  North          26.00
5   2023-01-06        B   54.0  Product3  192.0   West          54.00
6   2023-01-07        A   16.0  Product1  936.0   East          16.00
7   2023-01-08        C   89.0  Product1  488.0   West          89.00
8   2023-01-09        C   37.0  Product3  772.0   West          37.00
9   2023-01-10        A   22.0  Product2  834.0   West          22.00
10  2023-01-11        B    7.0  Product1  842.0  North           7.00
11  2023-01-12        B   60.0  Product2    NaN   West          60.00
12  2023-01-13        A   70.0  Product3  628.0  South          70.00
13  2023-01-14        A   69.0  Product1  423.0   East          69.00
14  2023-01-15        A   47.0  Product2  893.0   West          47.00
15  2023-01-16        C    NaN  Product1  895.0  North          48.64

In [41]:
#Renaming a column in the DataFrame using rename function
df.rename(columns={'Values_fillNA':'Value_filled_with_mean'})
df

          Date Category  Value   Product  Sales Region  Value_filled_with_mean
0   2023-01-01        A   28.0  Product1  754.0   East                   28.00
1   2023-01-02        B   39.0  Product3  110.0  North                   39.00
2   2023-01-03        C   32.0  Product2  398.0   East                   32.00
3   2023-01-04        B    8.0  Product1  522.0   East                    8.00
4   2023-01-05        B   26.0  Product3  869.0  North                   26.00
5   2023-01-06        B   54.0  Product3  192.0   West                   54.00
6   2023-01-07        A   16.0  Product1  936.0   East                   16.00
7   2023-01-08        C   89.0  Product1  488.0   West                   89.00
8   2023-01-09        C   37.0  Product3  772.0   West                   37.00
9   2023-01-10        A   22.0  Product2  834.0   West                   22.00
10  2023-01-11        B    7.0  Product1  842.0  North                    7.00
11  2023-01-12        B   60.0  Product2    NaN   West                   60.00
12  2023-01-13        A   70.0  Product3  628.0  South                   70.00
13  2023-01-14        A   69.0  Product1  423.0   East                   69.00
14  2023-01-15        A   47.0  Product2  893.0   West                   47.00
15  2023-01-16        C    NaN  Product1  895.0  North                   48.64
16  2023-01-17        C   93.0  Product2  511.0  South                   93.00
17  2023-01-18        C    NaN  Product1  108.0   West                   48.64
18  2023-01-19        A   31.0  Product2  578.0   West                   31.00
19  2023-01-20        A   59.0  Product1  736.0   East                   59.00
20  2023-01-21        C   82.0  Product3  606.0  South                   82.00
21  2023-01-22        C   37.0  Product2  992.0  South                   37.00
22  2023-01-23        B   62.0  Product3  942.0  North                   62.00
23  2023-01-24        C   92.0  Product2  342.0   West                   92.00
24  2023-01-25        A   24.0  Product2  458.0   East                   24.00
25  2023-01-26        C   95.0  Product1  584.0   West                   95.00
26  2023-01-27        C   71.0  Product2  619.0  North                   71.00
27  2023-01-28        C   56.0  Product2  224.0  North                   56.00
28  2023-01-29        B    NaN  Product3  617.0  North                   48.64
29  2023-01-30        C   51.0  Product2  737.0  South                   51.00
30  2023-01-31        B   50.0  Product3  735.0   West                   50.00
31  2023-02-01        A   17.0  Product2  189.0   West                   17.00
32  2023-02-02        B   63.0  Product3  338.0  South                   63.00
33  2023-02-03        C   27.0  Product3    NaN   East                   27.00
34  2023-02-04        C   70.0  Product3  669.0   West                   70.00
35  2023-02-05        B   60.0  Product2    NaN   West                   60.00
36  2023-02-06        C   36.0  Product3  177.0   East                   36.00
37  2023-02-07        C    2.0  Product1    NaN  North                    2.00
38  2023-02-08        C   94.0  Product1  408.0  South                   94.00
39  2023-02-09        A   62.0  Product1  155.0   West                   62.00
40  2023-02-10        B   15.0  Product1  578.0   East                   15.00
41  2023-02-11        C   97.0  Product1  256.0   East                   97.00
42  2023-02-12        A   93.0  Product3  164.0   West                   93.00
43  2023-02-13        A   43.0  Product3  949.0   East                   43.00
44  2023-02-14        A   96.0  Product3  830.0   East                   96.00
45  2023-02-15        B   99.0  Product2  599.0   West                   99.00
46  2023-02-16        B    6.0  Product1  938.0  South                    6.00
47  2023-02-17        B   69.0  Product3  143.0   West                   69.00
48  2023-02-18        C   65.0  Product3  182.0  North                   65.00
49  2023-02-19        C   11.0  Product3  708.0  North                   11.00

In [51]:
#Changing Datatype
from numpy import int64


df['new_Values']=df['Value'].fillna(df['Value'].mean()).astype(int64)
df.drop('new_Values', axis=1, inplace=True)
df

,Date,Category,Value,Product,Sales,Region,Value_filled_with_mean,New_Values
0,2023-01-01,A,28.0,Product1,754.0,East,28.00,28
1,2023-01-02,B,39.0,Product3,110.0,North,39.00,39
2,2023-01-03,C,32.0,Product2,398.0,East,32.00,32
3,2023-01-04,B,8.0,Product1,522.0,East,8.00,8
4,2023-01-05,B,26.0,Product3,869.0,North,26.00,26
5,2023-01-06,B,54.0,Product3,192.0,West,54.00,54
6,2023-01-07,A,16.0,Product1,936.0,East,16.00,16
7,2023-01-08,C,89.0,Product1,488.0,West,89.00,89
8,2023-01-09,C,37.0,Product3,772.0,West,37.00,37
9,2023-01-10,A,22.0,Product2,834.0,West,22.00,22
10,2023-01-11,B,7.0,Product1,842.0,North,7.00,7
11,2023-01-12,B,60.0,Product2,NaN,West,60.00,60
12,2023-01-13,A,70.0,Product3,628.0,South,70.00,70
13,2023-01-14,A,69.0,Product1,423.0,East,69.00,69
14,2023-01-15,A,47.0,Product2,893.0,West,47.00,47
15,2023-01-16,C,NaN,Product1,895.0,North,48.64,51
16,2023-01-17,C,93.0,Product2,511.0,South,93.00,93
17,2023-01-18,C,NaN,Product1,108.0,West,48.64,51
18,2023-01-19,A,31.0,Product2,578.0,West,31.00,31
19,2023-01-20,A,59.0,Product1,736.0,East,59.00,59
20,2023-01-21,C,82.0,Product3,606.0,South,82.00,82
21,2023-01-22,C,37.0,Product2,992.0,South,37.00,37
22,2023-01-23,B,62.0,Product3,942.0,North,62.00,62
23,2023-01-24,C,92.0,Product2,342.0,West,92.00,92
24,2023-01-25,A,24.0,Product2,458.0,East,24.00,24
25,2023-01-26,C,95.0,Product1,584.0,West,95.00,95
26,2023-01-27,C,71.0,Product2,619.0,North,71.00,71
27,2023-01-28,C,56.0,Product2,224.0,North,56.00,56
28,2023-01-29,B,NaN,Product3,617.0,North,48.64,51
29,2023-01-30,C,51.0,Product2,737.0,South,51.00,51
30,2023-01-31,B,50.0,Product3,735.0,West,50.00,50
31,2023-02-01,A,17.0,Product2,189.0,West,17.00,17
32,2023-02-02,B,63.0,Product3,338.0,South,63.00,63
33,2023-02-03,C,27.0,Product3,NaN,East,27.00,27
34,2023-02-04,C,70.0,Product3,669.0,West,70.00,70
35,2023-02-05,B,60.0,Product2,NaN,West,60.00,60
36,2023-02-06,C,36.0,Product3,177.0,East,36.00,36
37,2023-02-07,C,2.0,Product1,NaN,North,2.00,2
38,2023-02-08,C,94.0,Product1,408.0,South,94.00,94
39,2023-02-09,A,62.0,Product1,155.0,West,62.00,62
40,2023-02-10,B,15.0,Product1,578.0,East,15.00,15
41,2023-02-11,C,97.0,Product1,256.0,East,97.00,97
42,2023-02-12,A,93.0,Product3,164.0,West,93.00,93
43,2023-02-13,A,43.0,Product3,949.0,East,43.00,43
44,2023-02-14,A,96.0,Product3,830.0,East,96.00,96
45,2023-02-15,B,99.0,Product2,599.0,West,99.00,99
46,2023-02-16,B,6.0,Product1,938.0,South,6.00,6
47,2023-02-17,B,69.0,Product3,143.0,West,69.00,69
48,2023-02-18,C,65.0,Product3,182.0,North,65.00,65
49,2023-02-19,C,11.0,Product3,708.0,North,11.00,11

In [64]:
df['square_values']=df['Value']**2
#or df['square_values']=df['Value'].apply(lambda x: x**2) 
#to create a new column 'square_values' in the DataFrame df that contains the square of the values in the 'Value' column using apply function with lambda function. The result is stored in the new column 'square_values' and then printed to the console.
df.head()

,Date,Category,Value,Product,Sales,Region,Value_filled_with_mean,New_Values,square_values
0,2023-01-01,A,28.0,Product1,754.0,East,28.0,28,784.0
1,2023-01-02,B,39.0,Product3,110.0,North,39.0,39,1521.0
2,2023-01-03,C,32.0,Product2,398.0,East,32.0,32,1024.0
3,2023-01-04,B,8.0,Product1,522.0,East,8.0,8,64.0
4,2023-01-05,B,26.0,Product3,869.0,North,26.0,26,676.0

In [65]:
df

,Date,Category,Value,Product,Sales,Region,Value_filled_with_mean,New_Values,square_values
0,2023-01-01,A,28.0,Product1,754.0,East,28.00,28,784.0
1,2023-01-02,B,39.0,Product3,110.0,North,39.00,39,1521.0
2,2023-01-03,C,32.0,Product2,398.0,East,32.00,32,1024.0
3,2023-01-04,B,8.0,Product1,522.0,East,8.00,8,64.0
4,2023-01-05,B,26.0,Product3,869.0,North,26.00,26,676.0
5,2023-01-06,B,54.0,Product3,192.0,West,54.00,54,2916.0
6,2023-01-07,A,16.0,Product1,936.0,East,16.00,16,256.0
7,2023-01-08,C,89.0,Product1,488.0,West,89.00,89,7921.0
8,2023-01-09,C,37.0,Product3,772.0,West,37.00,37,1369.0
9,2023-01-10,A,22.0,Product2,834.0,West,22.00,22,484.0
10,2023-01-11,B,7.0,Product1,842.0,North,7.00,7,49.0
11,2023-01-12,B,60.0,Product2,NaN,West,60.00,60,3600.0
12,2023-01-13,A,70.0,Product3,628.0,South,70.00,70,4900.0
13,2023-01-14,A,69.0,Product1,423.0,East,69.00,69,4761.0
14,2023-01-15,A,47.0,Product2,893.0,West,47.00,47,2209.0
15,2023-01-16,C,NaN,Product1,895.0,North,48.64,51,NaN
16,2023-01-17,C,93.0,Product2,511.0,South,93.00,93,8649.0
17,2023-01-18,C,NaN,Product1,108.0,West,48.64,51,NaN
18,2023-01-19,A,31.0,Product2,578.0,West,31.00,31,961.0
19,2023-01-20,A,59.0,Product1,736.0,East,59.00,59,3481.0
20,2023-01-21,C,82.0,Product3,606.0,South,82.00,82,6724.0
21,2023-01-22,C,37.0,Product2,992.0,South,37.00,37,1369.0
22,2023-01-23,B,62.0,Product3,942.0,North,62.00,62,3844.0
23,2023-01-24,C,92.0,Product2,342.0,West,92.00,92,8464.0
24,2023-01-25,A,24.0,Product2,458.0,East,24.00,24,576.0
25,2023-01-26,C,95.0,Product1,584.0,West,95.00,95,9025.0
26,2023-01-27,C,71.0,Product2,619.0,North,71.00,71,5041.0
27,2023-01-28,C,56.0,Product2,224.0,North,56.00,56,3136.0
28,2023-01-29,B,NaN,Product3,617.0,North,48.64,51,NaN
29,2023-01-30,C,51.0,Product2,737.0,South,51.00,51,2601.0
30,2023-01-31,B,50.0,Product3,735.0,West,50.00,50,2500.0
31,2023-02-01,A,17.0,Product2,189.0,West,17.00,17,289.0
32,2023-02-02,B,63.0,Product3,338.0,South,63.00,63,3969.0
33,2023-02-03,C,27.0,Product3,NaN,East,27.00,27,729.0
34,2023-02-04,C,70.0,Product3,669.0,West,70.00,70,4900.0
35,2023-02-05,B,60.0,Product2,NaN,West,60.00,60,3600.0
36,2023-02-06,C,36.0,Product3,177.0,East,36.00,36,1296.0
37,2023-02-07,C,2.0,Product1,NaN,North,2.00,2,4.0
38,2023-02-08,C,94.0,Product1,408.0,South,94.00,94,8836.0
39,2023-02-09,A,62.0,Product1,155.0,West,62.00,62,3844.0
40,2023-02-10,B,15.0,Product1,578.0,East,15.00,15,225.0
41,2023-02-11,C,97.0,Product1,256.0,East,97.00,97,9409.0
42,2023-02-12,A,93.0,Product3,164.0,West,93.00,93,8649.0
43,2023-02-13,A,43.0,Product3,949.0,East,43.00,43,1849.0
44,2023-02-14,A,96.0,Product3,830.0,East,96.00,96,9216.0
45,2023-02-15,B,99.0,Product2,599.0,West,99.00,99,9801.0
46,2023-02-16,B,6.0,Product1,938.0,South,6.00,6,36.0
47,2023-02-17,B,69.0,Product3,143.0,West,69.00,69,4761.0
48,2023-02-18,C,65.0,Product3,182.0,North,65.00,65,4225.0
49,2023-02-19,C,11.0,Product3,708.0,North,11.00,11,121.0